export class ExternalUser {
    USER_ID: number;
    USER_NAME: string;
    PRACTICE_CODE: number;
    PASSWORD: string;
    FAILED_PASSWORD_ATTEMPT_COUNT: number;
    PASSWORD_CHANGED_DATE: Date;
    FIRST_NAME: string;
    LAST_NAME: string;
    DESIGNATION: string;
    IS_ADMIN: boolean;
    STATUS: number;
    MIDDLE_NAME: string;
    USER_DISPLAY_NAME: string;
    DATE_OF_BIRTH: Date;
    EMAIL: string;
    RESET_PASS: number;
    SECURITY_QUESTION: string;
    SECURITY_QUESTION_ANSWER: string;
    LOCKEDBY: string;
    IS_LOCKED_OUT: boolean;
    LAST_LOGIN_DATE: Date;
    COMMENTS: string;
    PASS_RESET_CODE: string;
    ACTIVATION_CODE: string;
    IS_ACTIVE: boolean = true;
    PHONE_NO: string;
    ROLE_ID: number;
    ADDRESS_1: string;
    ADDRESS_2: string;
    CITY: string;
    STATE: string;
    ZIP: string;
    CREATED_BY: string;
    CREATED_DATE: Date;
    MODIFIED_BY: string;
    MODIFIED_DATE: Date;
    DELETED: boolean;
    MANAGER_ID: number;
    ROLE_NAME: string;
    TOTAL_RECORD_PAGES: number;
    TOTAL_RECORDS: number;
    USER_TYPE: string = "Internal";
    PRACTICE_NAME: string = "";
    SENDER_TYPE: string = "";
    NPI: string = "";
    MOBILE_PHONE: string;
    FAX: string;
    FAX_2: string;
    FAX_3: string;
    GENDER: string;
    LANGUAGE: string;
    TIME_ZONE: string;
    TERMINATION_DATE: Date;
    SIGNATURE_PATH: string;
    TERMINATION_DATE_STR: string = "";
    FOX_TBL_SENDER_TYPE_ID: number;
    WORK_PHONE: string;
    NOTE_ID: number;
    ACO: number;
    SPECIALITY: number;
    SNF: number;
    HOSPITAL: number;
    HHH: number;
    THIRD_PARTY_REFERRAL_SOURCE: string;
    COMMENT: string;
    PRACTICE_ORGANIZATION_ID: number;
    IS_APPROVED: boolean;
    SPECIALITY_NAME: string;
    SNF_NAME: string;
    HOSPITAL_NAME: string;
    HHH_NAME: string;
    ACO_NAME: string;
    PRACTICE_ORGANIZATION_TEXT: string;
    ACO_TEXT: string;
    SPECIALITY_TEXT: string;
    SNF_TEXT: string;
    HOSPITAL_TEXT: string;
    HHH_TEXT: string;
    Is_Electronic_POC:boolean;
    constructor() {
        this.USER_ID = 0;
        this.ROLE_ID = 0;
        this.Is_Electronic_POC = true;
    }
}
