export class SmartSearchRequest {
    Keyword: string;
    PRACTICE_CODE: number;
    TYPE: string;
    SEARCHVALUE: string;
    CODE: string;
    DESCRIPTION: string;
    OPTIONSEARCH: string;
    PROVIDER_CODE: string;
    CODE_TYPE: string;
    CATEGORY: string;
    DOS: string;
    SenderTypeId: number;
    FINANCIAL_CLASS_ID: number;
    SearchValue: string;
    Insurance_Name: string;
    Pri_Sec_Oth_Type: string;
    Patient_Account: string;
    PROCDESCRIPTION: string;
    PROCCODE: string;
    LOCATION_CODE: string;
    PracticeCode: number;
    UserName: string;
    searchString: string;
    RecordPerPage: number;
    CurrentPage: number;
    Zip:string;
    State:string;
    Is_From_RFO: boolean;
}
